### ISSUE TITLE
Github Actions workflow izveidošana

### ISSUE THREAD

**Issue by edzya** [edzya/Fitness_tracker#11]
- [ ]  Izveidot Github Actions workflow, lai veiktu testus
- [ ]  Izveidot workflow priekš uzstādīšanas testa vidē

**Comment by KasparsBlums** [comment]
Repozitorijā izveidoti 3 Actions:

`AWS EC2 instace check`

`AWS EC2 START instaces`

`AWS EC2 STOP instaces`
